services:
    backend:
        build:
            context: .
            tags:
                - "circuit-stash-backend:latest"
        image: "circuit-stash-backend:latest"
        volumes:
            - ./data:/app/data
        environment:
            - LOG_LEVEL=DEBUG
        ports:
            - "8000:8000"
