site_name: My Docs

theme:
  name: "material"
  palette:
    scheme: "slate"
  features:
    - search.suggest
    - search.highlight

plugins:
  - mkdocstrings
  - search
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true
